Feature: Add tasks
AY2122S1-CS2113T-W12-4/tp pull request #48
Opened 2021-10-04 15:44 UTC by alvynben

Fixes #39 .

Expected User Output:

```
                                                                        
   ad88              88           88                                    
  d8"                ""           88                             ,d     
  88                              88                             88     
MM88MMM  8b,dPPYba,  88   ,adPPYb,88   ,adPPYb,d8   ,adPPYba,  MM88MMM  
  88     88P'   "Y8  88  a8"    `Y88  a8"    `Y88  a8P_____88    88     
  88     88          88  8b       88  8b       88  8PP"""""""    88     
  88     88          88  "8a,   ,d88  "8a,   ,d88  "8b,   ,aa    88,    
  88     88          88   `"8bbdP"Y8   `"YbbdP"Y8   `"Ybbd8"'    "Y888  
                                       aa,    ,88                       
                                        "Y8bbdP"                        
Hello!
What would you like to do?
_____________________________________
add burger /2021-09-23
_____________________________________
You have successfully added:
    burger | 2021-09-23
```

2021-10-04 16:07 UTC, zonglun99 reviewed
Very minor changes, other than that it looks good

2021-10-04 16:07 UTC, zonglun99 commented on src/main/java/seedu/commands/AddCommand.java
> +
Just a minor thing, can delete these spaces

2021-10-04 16:21 UTC, BryanElmer requested changes
Minor changes, other than that LGTM!

2021-10-04 16:21 UTC, BryanElmer commented on src/main/java/seedu/parser/Parser.java
> +        LocalDate expiryDate = LocalDate.parse(splitUserInput[2].replace("/",""));
Maybe can add a space after the comma

2021-10-04 16:21 UTC, BryanElmer commented on src/main/java/seedu/fridget/Fridget.java
> +            c.execute(ui,parser,ingredientList);
Maybe can add spaces after the commas here to make the code consistent :)

2021-10-04 16:41 UTC, alvynben commented on src/main/java/seedu/commands/Command.java
>       * @throws FridgetException exception thrown when Command class is executed.
Done!

2021-10-04 16:41 UTC, alvynben commented on src/main/java/seedu/commands/AddCommand.java
> +
Done!

2021-10-04 16:43 UTC, alvynben commented on src/main/java/seedu/ui/Ui.java
> +        System.out.println("    " + ingredient);
Done!

2021-10-04 16:45 UTC, alvynben commented on src/main/java/seedu/parser/Parser.java
> +        LocalDate expiryDate = LocalDate.parse(splitUserInput[2].replace("/",""));
Done!

2021-10-04 19:02 UTC, uosjapuelks approved these changes
Looks good

2021-10-05 02:59 UTC, zonglun99 approved these changes

2021-10-05 04:08 UTC, BryanElmer approved these changes
Looks good!

2021-10-05 04:17 UTC, merged